# Generated by Django 4.1.3 on 2022-12-10 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_lottype_parkinglot_user_avater_user_car_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingticket',
            name='enter_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='exit_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
