# Generated by Django 4.1.3 on 2022-12-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parkingticket_enter_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingticket',
            name='exit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
