# Generated by Django 4.1.3 on 2022-12-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_parkingticket_enter_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='enter_time2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='enter_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
