# Generated by Django 4.1.3 on 2022-12-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
